### ISSUE TITLE
[Bug]1.21.1 Crash - v3.1.0 not compatible

### ISSUE THREAD

**Issue by kingstairs** [Aton-Kish/reinforced-shulker-boxes#83]
### Describe the bug

Testing whether RSB 3.1.0 (for 1.21) still works with 1.21.1 - apparently doesn't. In creative mode, just trying to find it in the block menu crashes Minecraft

### To Reproduce

Minecraft 1.21.1, Fabric
The only mods installed were Fabric API and Reinforced barrels/chests/shulkers.

1. Launch a world in Creative mode
2. Open the inventory
3. Look for a reinforced shulker under functional blocks
4. Crash

Note that if RSB is disabled, you can see the Reinforced Barrels/Chests in creative and select them, but if you try and place it in the world, the game crashes (I think that's a different bug). Very reproducible.

### Expected behavior

To be able to select and create a reinforced shulker box. A bit surprised since I understand 1.21.1 is a very minor update to 1.21.0.

### Environment

- Minecraft:1.21.1
- Fabric Loader: 0.16.1
- Fabric API: 0.102.1

### Logs

```log
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-08-20 19:42:01
Description: Rendering item

java.lang.IllegalStateException: Invalid block entity minecraft:shulker_box // atonkish.reinfshulker.block.entity.ReinforcedShulkerBoxBlockEntity state at class_2338{x=0, y=0, z=0}, got Block{reinfshulker:copper_shulker_box}[facing=up]
	at net.minecraft.class_2586.method_61175(class_2586.java:57)
	at net.minecraft.class_2586.<init>(class_2586.java:51)
	at net.minecraft.class_2624.<init>(class_2624.java:33)
	at net.minecraft.class_2621.<init>(class_2621.java:25)
	at net.minecraft.class_2627.<init>(class_2627.java:63)
	at atonkish.reinfshulker.block.entity.ReinforcedShulkerBoxBlockEntity.<init>(ReinforcedShulkerBoxBlockEntity.java:35)
	at atonkish.reinfshulker.ReinforcedShulkerBoxesClientMod.lambda$initializeReinforcedShulkerBoxesClient$0(ReinforcedShulkerBoxesClientMod.java:75)
	at net.minecraft.class_756.handler$zka000$fabric-rendering-v1$fabric_onRender(class_756.java:541)
	at net.minecraft.class_756.method_3166(class_756.java)
	at net.minecraft.class_918.method_23179(class_918.java:127)
	at net.minecraft.class_332.method_51425(class_332.java:582)
	at net.minecraft.class_332.method_51424(class_332.java:564)
	at net.minecraft.class_332.method_51428(class_332.java:544)
	at net.minecraft.class_465.method_2385(class_465.java:257)
	at net.minecraft.class_465.method_25394(class_465.java:113)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_481.method_25394(class_481.java:778)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$177(class_757.java)
	at net.minecraft.class_757.wrapOperation$zmg000$fabric-screen-api-v1$onRenderScreen(class_757.java:2086)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2586.method_61175(class_2586.java:57)
	at net.minecraft.class_2586.<init>(class_2586.java:51)
	at net.minecraft.class_2624.<init>(class_2624.java:33)
	at net.minecraft.class_2621.<init>(class_2621.java:25)
	at net.minecraft.class_2627.<init>(class_2627.java:63)
	at atonkish.reinfshulker.block.entity.ReinforcedShulkerBoxBlockEntity.<init>(ReinforcedShulkerBoxBlockEntity.java:35)
	at atonkish.reinfshulker.ReinforcedShulkerBoxesClientMod.lambda$initializeReinforcedShulkerBoxesClient$0(ReinforcedShulkerBoxesClientMod.java:75)
	at net.minecraft.class_756.handler$zka000$fabric-rendering-v1$fabric_onRender(class_756.java:541)
	at net.minecraft.class_756.method_3166(class_756.java)
	at net.minecraft.class_918.method_23179(class_918.java:127)
	at net.minecraft.class_332.method_51425(class_332.java:582)
	at net.minecraft.class_332.method_51424(class_332.java:564)
	at net.minecraft.class_332.method_51428(class_332.java:544)
	at net.minecraft.class_465.method_2385(class_465.java:257)
	at net.minecraft.class_465.method_25394(class_465.java:113)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_481.method_25394(class_481.java:778)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$177(class_757.java)
	at net.minecraft.class_757.wrapOperation$zmg000$fabric-screen-api-v1$onRenderScreen(class_757.java:2086)

-- Item being rendered --
Details:
	Item Type: reinfshulker:copper_shulker_box
	Item Components: {minecraft:max_stack_size=>1, minecraft:lore=>class_9290[lines=[], styledLines=[]], minecraft:enchantments=>ItemEnchantments{enchantments={}, showInTooltip=true}, minecraft:repair_cost=>0, minecraft:attribute_modifiers=>class_9285[modifiers=[], showInTooltip=true], minecraft:rarity=>COMMON}
	Item Foil: false
Stacktrace:
	at net.minecraft.class_332.method_51425(class_332.java:582)
	at net.minecraft.class_332.method_51424(class_332.java:564)
	at net.minecraft.class_332.method_51428(class_332.java:544)
	at net.minecraft.class_465.method_2385(class_465.java:257)
	at net.minecraft.class_465.method_25394(class_465.java:113)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_481.method_25394(class_481.java:778)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$177(class_757.java)
	at net.minecraft.class_757.wrapOperation$zmg000$fabric-screen-api-v1$onRenderScreen(class_757.java:2086)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (291, 144). Absolute: (583.000000, 288.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 54.372s
	Wall uptime: 45.006s
	High-res time: 43.855s
	Client ticks: 748 ticks / 37.400s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```

**Comment by Aton-Kish** [comment]
fixed this issue in v3.2.0+1.21.1.
